apiVersion: v1
data: null
kind: ConfigMap
metadata:
  labels:
    app: webhook
    app.kubernetes.io/component: webhook
    app.kubernetes.io/instance: webhook
    app.kubernetes.io/name: webhook
  name: webhook
  namespace: cert-manager
