apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../modules/argocd-mgmt
  - ingress.yaml
  - projects


namespace: argocd
patches:
  - path: controller-patch.yaml
    target:
      kind: StatefulSet
      name: argocd-application-controller
