---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: ipwhitelist
  namespace: traefik
spec:
  ipWhiteList:
    sourceRange:
      - 127.0.0.1/32
      - 194.168.230.96/29 # cts office
      - 35.189.218.0/32 # cts vpn
      - 92.13.99.107/32 # home network
