---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: traefik-ingress-controllercouchbase-db
  namespace: kube-system
  labels:
    k8s-app: traefik-ingress-lb
spec:
  selector:
    matchLabels:
      k8s-app: traefik-ingress-lb
  maxUnavailable: 1