---
apiVersion: v1
kind: List
metadata:
  name: traefik-ingress-controller
  namespace: traefik
items:
  - apiVersion: v1
    kind: Service
    metadata:
      name: traefik-ingress-controller
      labels:
        app.kubernetes.io/name: traefik
        app.kubernetes.io/instance: traefik
      annotations:
    spec:
      type: LoadBalancer
      selector:
        app.kubernetes.io/name: traefik
        app.kubernetes.io/instance: traefik
      ports:
        - port: 80
          name: web
          targetPort: "web"
          protocol: "TCP"
        - port: 443
          name: websecure
          targetPort: "websecure"
          protocol: "TCP"
---
apiVersion: v1
kind: Service
metadata:
  name: traefik-web-ui
  namespace: traefik
spec:
  selector:
    app.kubernetes.io/name: traefik
    app.kubernetes.io/instance: traefik
  ports:
    - name: web
      port: 80
      targetPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: traefik-metrics
  namespace: traefik
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8888"
spec:
  selector:
    app.kubernetes.io/name: traefik
    app.kubernetes.io/instance: traefik
  ports:
    - name: metrics
      port: 8888
      targetPort: 9100
