apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  destination:
    namespace: argocd
    server: "https://kubernetes.default.svc"
  source:
    repoURL: "git@github.com:dsmillie-cts/sandbox-k8s.git"
    targetRevision: master
    path: live/mgmt/argocd
  syncPolicy:
    automated: {}
